# Generated by Django 5.0.3 on 2024-04-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureconnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField()),
            ],
        ),
    ]
