# Generated by Django 5.0.3 on 2024-04-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coutureconnect', '0003_service_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
    ]
