# Generated by Django 5.0.3 on 2024-05-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coutureconnect', '0005_event_profile_threadmodel_messagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
